FROM ubuntu:groovy

# Else the installation of GNOME Shell will ask interactively for our time zone.
ENV DEBIAN_FRONTEND noninteractive

# Install GNOME Session, xvfb, and xdotool. Then apply the patch and remove an incomplete
# Ubuntu extension to prevent an error when GNOME Shell tries to load it.
RUN apt update -y &&                                                                     \
    apt install -y gnome-session gnome-shell-extension-prefs                             \
                   sudo xvfb xdotool libglib2.0-dev-bin patch &&                         \
    rm -r /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com &&                    \
    apt remove -y libglib2.0-dev-bin patch &&                                            \
    apt autoremove -y

# Start Xvfb via systemd on display :99.
COPY xvfb@.service /etc/systemd/system
RUN systemctl enable xvfb@:99.service &&                                                 \
    systemctl set-default multi-user.target

# The first is required to make systemd-logind work, the second
# makes sure that the gnomeshell user gets logged in automatically.
RUN mkdir -p /etc/systemd/system/systemd-logind.service.d &&                             \
    { echo "[Service]";                                                                  \
      echo "ProtectHostname=no";                                                         \
    } > /etc/systemd/system/systemd-logind.service.d/override.conf &&                    \
    mkdir -p /etc/systemd/system/console-getty.service.d &&                              \
    { echo "[Service]";                                                                  \
      echo "ExecStart=";                                                                 \
      echo "ExecStart=-/sbin/getty --autologin gnomeshell --noclear                      \
                                   --keep-baud console 115200,38400,9600 $TERM";         \
    } > /etc/systemd/system/console-getty.service.d/override.conf

# Add the gnomeshell user with no password.
RUN adduser --disabled-password --gecos "" gnomeshell &&                                 \
    usermod -a -G adm gnomeshell &&                                                      \
    echo "gnomeshell     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Add the scripts.
COPY enable-extension.sh set-env.sh .profile /home/gnomeshell

CMD [ "/usr/sbin/init" ]